<?php
/** Authenticated customer portal shell. @package Arvan_Reseller */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
$settings   = wp_parse_args( get_option( 'arvan_reseller_settings', array() ), array( 'company_name' => '', 'company_logo_url' => '', 'mode' => 'mock' ) );
$mode       = 'live' === $settings['mode'] ? 'live' : 'mock';
$mode_label = 'live' === $mode ? __( 'زنده', 'arvan-reseller' ) : __( 'آزمایشی', 'arvan-reseller' );
$nav        = array(
	'dashboard'     => array( __( 'داشبورد', 'arvan-reseller' ), 'grid', 'nav.dashboard' ),
	'services'      => array( __( 'سرویس‌ها', 'arvan-reseller' ), 'server', 'nav.services' ),
	'create-server' => array( __( 'ساخت سرور', 'arvan-reseller' ), 'plus', 'nav.createServer' ),
	'wallet'        => array( __( 'کیف پول', 'arvan-reseller' ), 'wallet', 'nav.wallet' ),
	'billing'       => array( __( 'مصرف و صورتحساب‌ها', 'arvan-reseller' ), 'chart', 'nav.billing' ),
	'orders'        => array( __( 'سفارش‌ها', 'arvan-reseller' ), 'receipt', 'nav.orders' ),
	'notifications' => array( __( 'اعلان‌ها', 'arvan-reseller' ), 'bell', 'nav.notifications' ),
);
?>
<section class="arvan-reseller-app ar-customer-portal" dir="rtl" lang="fa" data-ar-context="customer" data-ar-route="dashboard">
	<a class="ar-skip-link" href="#ar-customer-main"><?php esc_html_e( 'پرش به محتوای اصلی', 'arvan-reseller' ); ?></a>
	<div class="ar-app-frame">
		<aside class="ar-sidebar" aria-label="<?php esc_attr_e( 'ناوبری پنل مشتری', 'arvan-reseller' ); ?>">
			<a class="ar-brand" href="<?php echo esc_url( get_permalink() ); ?>"><?php if ( '' !== (string) $settings['company_logo_url'] ) : ?><img class="ar-brand__logo" src="<?php echo esc_url( $settings['company_logo_url'] ); ?>" alt="" /><?php else : ?><span class="ar-brand__mark" aria-hidden="true"><span class="ar-icon"><svg viewBox="0 0 24 24"><path d="M17.5 19H7a5 5 0 0 1-.8-9.94A7 7 0 0 1 19.5 11a4 4 0 0 1-2 8z"/></svg></span></span><?php endif; ?><span><strong><?php echo esc_html( (string) $settings['company_name'] ?: __( 'فروش ابری آروان', 'arvan-reseller' ) ); ?></strong><small data-ar-i18n="shell.cloudPanel"><?php esc_html_e( 'پنل ابری', 'arvan-reseller' ); ?></small></span></a>
			<nav class="ar-sidebar__nav">
				<?php foreach ( $nav as $key => $item ) : ?><button class="ar-nav-item<?php echo 'dashboard' === $key ? ' is-active' : ''; ?>" type="button" data-ar-route="<?php echo esc_attr( $key ); ?>"<?php echo 'dashboard' === $key ? ' aria-current="page"' : ''; ?>><span class="ar-icon" data-icon="<?php echo esc_attr( $item[1] ); ?>" aria-hidden="true"></span><span data-ar-i18n="<?php echo esc_attr( $item[2] ); ?>"><?php echo esc_html( $item[0] ); ?></span></button><?php endforeach; ?>
			</nav>
			<div class="ar-sidebar__footer"><span class="ar-env ar-env--<?php echo esc_attr( $mode ); ?>"><span></span><?php echo esc_html( $mode_label ); ?></span><a href="<?php echo esc_url( wp_logout_url( home_url( '/' ) ) ); ?>" data-ar-i18n="shell.logout"><?php esc_html_e( 'خروج از حساب', 'arvan-reseller' ); ?></a></div>
		</aside>
		<div class="ar-workspace">
			<header class="ar-topbar"><button class="ar-icon-button ar-mobile-menu" type="button" data-ar-action="toggle-sidebar" aria-label="<?php esc_attr_e( 'بازکردن ناوبری', 'arvan-reseller' ); ?>" aria-expanded="false"><span class="ar-icon" data-icon="menu" aria-hidden="true"></span></button><div><strong id="ar-customer-page-title" data-ar-i18n="nav.dashboard"><?php esc_html_e( 'داشبورد', 'arvan-reseller' ); ?></strong><small><?php printf( esc_html__( 'خوش آمدید، %s', 'arvan-reseller' ), esc_html( $user->display_name ) ); ?></small></div><div class="ar-topbar__actions"><div class="ar-preference-controls"><div class="ar-segmented ar-language-toggle" data-ar-language-toggle role="group" aria-label="<?php esc_attr_e( 'زبان نمایش', 'arvan-reseller' ); ?>" data-ar-i18n-label="preference.language"><button type="button" data-ar-language-value="fa" aria-pressed="true"><bdi>FA</bdi></button><button type="button" data-ar-language-value="en" aria-pressed="false"><bdi>EN</bdi></button></div><div class="ar-segmented ar-theme-toggle" data-ar-theme-toggle role="group" aria-label="<?php esc_attr_e( 'پوسته نمایش', 'arvan-reseller' ); ?>" data-ar-i18n-label="preference.theme"><button type="button" data-ar-theme-value="light" aria-pressed="false"><span class="ar-icon" data-icon="theme" aria-hidden="true"></span><span data-ar-i18n="preference.light"><?php esc_html_e( 'روشن', 'arvan-reseller' ); ?></span></button><button type="button" data-ar-theme-value="dark" aria-pressed="false"><span class="ar-icon" data-icon="moon" aria-hidden="true"></span><span data-ar-i18n="preference.dark"><?php esc_html_e( 'تیره', 'arvan-reseller' ); ?></span></button></div></div><span class="ar-env ar-env--<?php echo esc_attr( $mode ); ?>"><span></span><?php echo esc_html( $mode_label ); ?></span><button class="ar-icon-button" type="button" data-ar-route="notifications" aria-label="<?php esc_attr_e( 'اعلان‌ها', 'arvan-reseller' ); ?>"><span class="ar-icon" data-icon="bell" aria-hidden="true"></span></button><button class="ar-avatar ar-account-trigger" type="button" data-ar-action="toggle-account" aria-expanded="false" aria-controls="ar-account-drawer" aria-label="<?php esc_attr_e( 'بازکردن حساب مشتری', 'arvan-reseller' ); ?>" data-ar-i18n-label="account.open"><?php echo esc_html( function_exists( 'mb_substr' ) ? mb_substr( $user->display_name, 0, 1 ) : substr( $user->display_name, 0, 1 ) ); ?></button></div></header>
			<main class="ar-main" id="ar-customer-main" tabindex="-1"><div id="ar-customer-content" class="ar-page" aria-live="polite"><div class="ar-loading-state"><span class="ar-spinner" aria-hidden="true"></span><p><?php esc_html_e( 'در حال آماده‌سازی پنل ابری...', 'arvan-reseller' ); ?></p></div></div></main>
		</div>
	</div>
	<aside class="ar-account-drawer" id="ar-account-drawer" data-ar-account-drawer role="dialog" aria-modal="true" aria-labelledby="ar-account-title" tabindex="-1" hidden><header><div><span class="ar-eyebrow" data-ar-i18n="account.title"><?php esc_html_e( 'حساب مشتری', 'arvan-reseller' ); ?></span><h2 id="ar-account-title"><?php echo esc_html( $user->display_name ); ?></h2><p dir="ltr"><?php echo esc_html( $user->user_email ); ?></p></div><button class="ar-icon-button" type="button" data-ar-action="close-account" aria-label="<?php esc_attr_e( 'بستن حساب', 'arvan-reseller' ); ?>"><span class="ar-icon" data-icon="close" aria-hidden="true"></span></button></header><div class="ar-account-drawer__content" data-ar-account-content><div class="ar-loading-state"><span class="ar-spinner" aria-hidden="true"></span><p><?php esc_html_e( 'در حال دریافت خلاصه حساب…', 'arvan-reseller' ); ?></p></div></div><footer><button class="ar-button ar-button--accent" type="button" data-ar-route="create-server"><span class="ar-icon" data-icon="plus" aria-hidden="true"></span><span data-ar-i18n="action.newService"><?php esc_html_e( 'سرویس جدید', 'arvan-reseller' ); ?></span></button><a class="ar-button ar-button--secondary" href="<?php echo esc_url( wp_logout_url( home_url( '/' ) ) ); ?>" data-ar-i18n="action.logout"><?php esc_html_e( 'خروج از حساب', 'arvan-reseller' ); ?></a></footer></aside><button class="ar-account-scrim" type="button" data-ar-action="close-account" aria-label="<?php esc_attr_e( 'بستن حساب مشتری', 'arvan-reseller' ); ?>" hidden></button>
	<nav class="ar-bottom-nav" aria-label="<?php esc_attr_e( 'ناوبری موبایل', 'arvan-reseller' ); ?>"><?php foreach ( array( 'dashboard', 'services', 'wallet', 'notifications' ) as $key ) : ?><button type="button" data-ar-route="<?php echo esc_attr( $key ); ?>" class="<?php echo 'dashboard' === $key ? 'is-active' : ''; ?>"><span class="ar-icon" data-icon="<?php echo esc_attr( $nav[ $key ][1] ); ?>" aria-hidden="true"></span><span data-ar-i18n="<?php echo esc_attr( $nav[ $key ][2] ); ?>"><?php echo esc_html( $nav[ $key ][0] ); ?></span></button><?php endforeach; ?></nav>
	<div class="ar-toast-region" aria-live="polite" aria-atomic="true"></div><div class="ar-modal-root"></div><div class="ar-sidebar-scrim" data-ar-action="close-sidebar" hidden></div>
</section>
